### ISSUE TITLE
UITextField Scrolling

### ISSUE THREAD

**Issue by NicholiP** [hoiberg/swiftBluetoothSerial#3]
Good Day,

First off your tutorials and Serial Pro have helped immensely. I am very new to Swift Coding and currently attempting a simpler version of serial that allows me to view six sensors data sent as character. I am using UITextfield to display updated characteristic but I am running into an issue of the text is scrolling much like the serial app. is there a way to keep TextField from scrolling and just updating Text? Any advice is appreciated and much thanks for your time and app!

**Comment by hoiberg** [comment]
You can uncomment the calls to `textViewScrollToBottom()` in SerialViewController to disable the automatic scrolling. In the Pro app there is a setting in the Display Options to disable scrolling.
Good luck with your project :]

**Comment by NicholiP** [comment]
Thank you for the response 

I have attempted commenting out that function and it is not scrolling but the new characters are still being added to the new line of the old characters. 
I I believe what is causing it is 
func serialDidRecieveString(_message: String){
MainTextView.text! += message
 
If the += is changed to just = the text is replaced but is only showing one line that runs through all six characters quickly. But having the += allows all characters to appear  correctly. Is there a way to have the text clear and print over the old text?
Again thank you. I’m sure you receive a lot of questions and I appreciate your time. 

Best regards
Nicholas

**Comment by hoiberg** [comment]
If the message is of fixed length, you can do something like this:

```
var string = ""

func serialDidReceiveString(_ message: String) {
  for c in message {
    string.append(c)
    if string.count == EXPECTED_LENGTH {
      textView.text = string
      string = ""
    }
}
```

If they are not of fixed length, you'll have to come up with a custom protocol to send the messages with (for example, add a line break character at the end of each sent message).
